version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - n 22
      - node -v  # Check the installed Node.js version
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Building the project...
      - npm run build

artifacts:
  files:
    - dist/**/*
