version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps
      - echo "Checking file permissions..."
      - ls -la node_modules/.bin
      - ls -la node_modules/.bin/tsup
      - echo "Checking executable permissions for tsup..."
      - if [ -x "$(command -v tsup)" ]; then echo "tsup is executable"; else echo "tsup is not executable"; fi

  build:
    commands:
      - echo "Building the project..."
      - export PATH=$PATH:./node_modules/.bin
      - npm run build

artifacts:
  files:
    - dist/**/*
